---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-demo
  source:
    chart: vela-core
    repoURL: https://sanyu.github.io/helm-charts/
    targetRevision: "1.4.6"
    helm:
      parameters:
        - name: multicluster.clusterGateway.secureTLS.certManager.enabled
          value: "true"
        - name: multicluster.metrics.enabled
          value: "true"
        - name: multicluster.clusterGateway.secureTLS.certManager.enabled
          value: "true"
  destination:
    namespace: vela-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: apiregistration.k8s.io
    kind: APIService
    jsonPointers:
    - /spec/caBundle
