---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-demo
  source:
    chart: ingress-nginx
    repoURL:  https://kubernetes.github.io/ingress-nginx
    targetRevision: "4.2.1"
    helm:
      parameters:
        - name: controller.metrics.enabled
          value: "true"
        - name: controller.metrics.service.annotations.prometheus\.io\/scrape
          value: "true"
          forceString: true
        - name: controller.metrics.service.annotations.prometheus\.io\/port
          value: "10254"
          forceString: true
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
