apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: xdemonetworks.aws.demo.com
  labels:
    provider: aws
spec:
  compositeTypeRef:
    apiVersion: aws.demo.com/v1alpha1
    kind: XDemoNetwork
  writeConnectionSecretsToNamespace: crossplane-system

  patchSets:
  - name: network-id
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.id
      toFieldPath: metadata.labels[networks.aws.demo.com/network-id]
  resources:
    - name: vpc
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: VPC
        metadata:
          labels:
            type: vpc
        spec:
          forProvider:
            region: ap-southeast-2
            enableDnsSupport: true
            enableDnsHostNames: true
            cidrBlock: 10.0.0.0/16
            tags:
            - key: Name
            - key: kubernetes.io/cluster/demo
              value: shared
      patches:
        - type: PatchSet
          patchSetName: network-id

        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: spec.id
            strategy: string
            string:
              fmt: "%s"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required

        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.tags[1].key
          type: FromCompositeFieldPath
          transforms:
            - type: string
              string:
                fmt: "kubernetes.io/cluster/%s"
                type: Format
          policy:
            fromFieldPath: Required

    - name: sg-nodes
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: SecurityGroup
        spec:
          forProvider:
            description: Cluster communication with worker nodes
            groupName: demo
            region: ap-southeast-2
            vpcIdSelector:
              matchControllerRef: true
            egress:
            - fromPort: null
              toPort: null
              ipProtocol: "-1"
              ipRanges:
              - cidrIp: "0.0.0.0/0"
      patches:
        - type: PatchSet
          patchSetName: network-id

    - name: nodes-subnets-2a
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: ap-southeast-2a
            access: private
            type: subnet
        spec:
          forProvider:
            region: ap-southeast-2
            availabilityZone: ap-southeast-2a
            cidrBlock: 10.0.0.0/24
            vpcIdSelector:
              matchControllerRef: true
            mapPublicIPOnLaunch: false
            tags:
              - key: Name
              - value: shared
              - key: access
                value: private
              - key: kubernetes.io/role/internal-elb
                value: "1"
      patches:
        - type: PatchSet
          patchSetName: network-id

        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: "%s-private-2a"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required

        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.tags[1].key
          type: FromCompositeFieldPath
          transforms:
            - type: string
              string:
                fmt: "kubernetes.io/cluster/%s"
                type: Format
          policy:
            fromFieldPath: Required

    - name: nodes-subnets-2b
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: ap-southeast-2b
            access: private
            type: subnet
        spec:
          forProvider:
            region: ap-southeast-2
            availabilityZone: ap-southeast-2b
            cidrBlock: 10.0.1.0/24
            vpcIdSelector:
              matchControllerRef: true
            mapPublicIPOnLaunch: false
            tags:
              - key: Name
              - value: shared
              - key: access
                value: private
              - key: kubernetes.io/role/internal-elb
                value: "1"
      patches:
        - type: PatchSet
          patchSetName: network-id
        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: "%s-private-2b"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required
        - fromFieldPath: spec.id
          toFieldPath: spec.forProvider.tags[1].key
          transforms:
            - type: string
              string:
                fmt: "kubernetes.io/cluster/%s"
                type: Format
          type: FromCompositeFieldPath
          policy:
            fromFieldPath: Required

    - name: nodes-subnets-public-2a
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: ap-southeast-2a
            access: public
            type: subnet
        spec:
          forProvider:
            region: ap-southeast-2
            availabilityZone: ap-southeast-2a
            cidrBlock: 10.0.200.0/24
            vpcIdSelector:
              matchControllerRef: true
            mapPublicIPOnLaunch: true
            tags:
              - key: Name
              - key: access
                value: public
              - key: kubernetes.io/role/elb
                value: "1"
      patches:
        - type: PatchSet
          patchSetName: network-id

        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: "%s-public-2a"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required

    - name: nodes-subnets-public-2b
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: Subnet
        metadata:
          labels:
            zone: ap-southeast-2b
            access: public
            type: subnet
        spec:
          forProvider:
            region: ap-southeast-2
            availabilityZone: ap-southeast-2b
            cidrBlock: 10.0.201.0/24
            vpcIdSelector:
              matchControllerRef: true
            mapPublicIPOnLaunch: true
            tags:
              - key: Name
              - key: access
                value: public
              - key: kubernetes.io/role/elb
                value: "1"
      patches:
        - type: PatchSet
          patchSetName: network-id

        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: "%s-public-2b"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required

    - name: gateway
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: InternetGateway
        metadata:
          labels:
            type: igw
        spec:
          forProvider:
            region: ap-southeast-2
            vpcIdSelector:
              matchControllerRef: true
      patches:
        - type: PatchSet
          patchSetName: network-id

    - name: routetable-public
      base:
        apiVersion: ec2.aws.crossplane.io/v1beta1
        kind: RouteTable
        spec:
          forProvider:
            region: ap-southeast-2
            vpcIdSelector:
              matchControllerRef: true
            routes:
              - destinationCidrBlock: 0.0.0.0/0
                gatewayIdSelector:
                  matchLabels:
                    type: igw
            associations:
              - subnetIdSelector:
                  matchLabels:
                    type: subnet
                    zone: ap-southeast-2a
                    access: public
              - subnetIdSelector:
                  matchLabels:
                    type: subnet
                    zone: ap-southeast-2b
                    access: public
            tags:
              - key: Name
      patches:
        - type: PatchSet
          patchSetName: network-id

        - type: CombineFromComposite
          combine:
            variables:
              - fromFieldPath: metadata.name
            strategy: string
            string:
              fmt: "%s-public-route-table"
          toFieldPath: spec.forProvider.tags[0].value
          policy:
            fromFieldPath: Required
