apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xdemonetworks.aws.demo.com
spec:
  group: aws.demo.com
  names:
    kind: XDemoNetwork
    plural: xdemonetworks
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                id:
                  type: string
                  description: ID of this Network
              required:
                - id
