---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-demo
  source:
    chart: external-dns
    repoURL:  https://charts.bitnami.com/bitnami
    targetRevision: "6.5.6"
    helm:
      parameters:
        - name: policy
          value: sync
        - name: aws.region
          value: ap-southeast-2
  destination:
    namespace: external-dns
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
