---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubevela-definitions
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-demo
  source:
    path: apps/kubevela-definitions
    repoURL: https://github.com/sanyu/platform-demo
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
