---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-demo
  source:
    chart: metrics-server
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "6.0.7"
    helm:
      parameters:
        - name: image.registry
          value: public.ecr.aws
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
