---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-demo
  source:
    chart: nginx-ingress-controller
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "9.2.13"
    helm:
      parameters:
        - name: fullnameOverride
          value: ingress-nginx
        - name: image.registry
          value: public.ecr.aws
        - name: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-backend-protocol
          value: tcp
        - name: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-cross-zone-load-balancing-enabled
          value: 'true'
        - name: service.annotations.service\.beta\.kubernetes\.io/aws-load-balancer-type
          value: nlb

  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
