apiVersion: core.oam.dev/v1beta1
kind: ComponentDefinition
metadata:
  name: frontend
  annotations:
    definition.oam.dev/description: "frontend"
spec:
  workload:
    definition:
      apiVersion: apps/v1
      kind: Deployment
  schematic:
    cue:
      template: |
        output: {
          apiVersion: "apps/v1"
          kind:       "Deployment"
          spec: {
            selector: matchLabels: {
              "app.oam.dev/component": context.name
              }
            template: {
              metadata: labels: {
                "app.oam.dev/component": context.name
              }
              spec: {
                containers: [{
                  name:  context.name
                  image: parameter.image
                  if parameter["cmd"] != _|_ {
                    command: parameter.cmd
                  }
                  imagePullPolicy: "Always"

                  ports: [{
                    containerPort: parameter.port
                    protocol: "TCP"
                  }]

                  if parameter.env != _|_ {
                    env: parameter.env
                  }

                }]
              }
            }
          }
        }
        #Env: {
          name:  string
          value: string
        }
        parameter: {
          image: string
          cmd?: [...string]
          port: *3000 | int
          env?: [...#Env]
        }
