apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- github.com/argoproj/argo-cd/manifests/crds?ref=v2.4.0
- github.com/argoproj/argo-cd/manifests/base?ref=v2.4.0
- github.com/argoproj/argo-cd/manifests/cluster-rbac?ref=v2.4.0
namespace: argocd
