apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - github.com/argoproj/argo-workflows/manifests/cluster-install?ref=v3.3.6
  - templates.yaml

patchesStrategicMerge:
  - config.yaml

patches:
  - target:
      kind: Deployment
      name: workflow-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/args/3
        value: quay.io/argoproj/argoexec:v3.3.6

namespace: argo

images:
  - name: quay.io/argoproj/argocli
    newTag: v3.3.6
  - name: quay.io/argoproj/workflow-controller
    newtag: v3.3.6
