apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ../../base
  - ingress.yaml


patches:

  - target:
      kind: StatefulSet
      name: argocd-application-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: application-controller
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe/tcpSocket
        value:
          port: 8082
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe/httpGet

  - target:
      kind: Deployment
      name: argocd-applicationset-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: applicationset-controller

  - target:
      kind: Deployment
      name: argocd-notifications-controller
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: notifications-controller

  - target:
      kind: Deployment
      name: argocd-repo-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: repo-server
      - op: remove
        path: /spec/template/spec/containers/0/readinessProbe/httpGet
      - op: remove
        path: /spec/template/spec/containers/0/livenessProbe/httpGet
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe/tcpSocket
        value:
          port: 8081
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe/tcpSocket
        value:
          port: 8081

  - target:
      kind: Deployment
      name: argocd-server
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: server

  - target:
      kind: Deployment
      name: argocd-redis
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: argocd-redis
      - op: replace
        path: /spec/template/spec/securityContext/runAsNonRoot
        value: false

patchesStrategicMerge:
  - server.yaml
  - repo-server.yaml
  - delete-np.yaml
