apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - ../../base
  - ingress.yaml

patches:

  - target:
      kind: StatefulSet
      name: argocd-application-controller
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: "--app-resync"
      - op: add
        path: /spec/template/spec/containers/0/command/-
        value: "30"

  - target:
      kind: Deployment
      name: argocd-redis
    patch: |-
      - op: replace
        path: /spec/template/spec/securityContext/runAsNonRoot
        value: false

patchesStrategicMerge:
  - server.yaml
  - repo-server.yaml
  - delete-np.yaml
  - argocd-cm.yaml
